### PR TITLE
Added chinese language support old

### PR DESCRIPTION
**Pull request by linksgo2011**
(Add a language pack, default to en, users need to manually modify the default language, then increase when creating select language.

### CODE REVIEW

**Comment by linksgo2011** [comment]
@ticup I submit some code, please check if wrong, increased international support, and a Chinese language pack

**Comment by ticup** [comment]
@linksgo2011 : Looks great!
I was just wondering if there is any way we could manage Cody's i18n in cody itself...

@jcoppieters If I'm correct, the cms interface is already written in cody itself, no? So we could easily insert linksgo's translations into the db?

Of course, this would also mean a more difficult upgrade transition, because people would need to update their databases, whereas with the json solution they can just update cody and it will work.

**Comment by linksgo2011** [comment]
@ticup  I have dealt with all the template on static text above, using the __ () package, so that we can convenient to internationalization of template, because users can modify the content of the database, so we only need to change the database content in the next version

**Comment by jcoppieters** [comment]
Let's try to merge this!
  I think the json locale files are a good choice.

but before we do:
- lin, can you add the locale setting to the config.json / cody.config and pick it up in doc/empty/index.js ?
  same way as we do the db, user, pw, etc...
- I'll make a Dutch file as second example

Questions:
- don't we need a "en" locale file and make the labels shorter?
- if we now correct a label in the program, we probably have to change all the locale files, no?

Johan.

**Comment by linksgo2011** [comment]
jcoppieters 

Because I am not familiar with the project, you may submit a change for me. I think whether can choose when creating a language? Make notes in the document, using the corresponding language themselves add language file


lin

**Comment by ticup** [comment]
@linksgo2011: Ok, here is what I suggest:

Redo the pull request, but now instead of doing a pull request from linksgo:master to jcoppieters:master, do a pull request from linksgo:master to the jcoppieters:i18n branch (I created it).

Like this I can just accept the pull request and then easily incorporate the suggested changes by @jcoppieters and then finally merge them into the master branch!

Thanks a bunch!!

**Comment by linksgo2011** [comment]
@ticup  Ok

**Comment by ticup** [comment]
See https://github.com/jcoppieters/cody/pull/31

**Comment by jcoppieters** [comment]
Wow thanks man!

Johan.

**Pull request closed without merging**
